#
# (C) Copyright 2015-2016 Theobroma Systems Design und Consulting GmbH
#                         Philipp Tomsich <philipp.tomsich@theobroma-systems.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-$(CONFIG_MACH_SUN8I_H3)	+= ddr3-1600k.o
obj-$(CONFIG_MACH_SUN50I)	+= ddr3-1600k.o

obj-y += util.o
endif
