#
# Copyright (c) 2017 Theobroma Systems Design und Consulting GmbH
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SUNXI_PINCTRL) += pinctrl-sunxi.o
ifdef CONFIG_SUNXI_PINCTRL
obj-$(CONFIG_MACH_SUN50I)   += pinctrl-sun50i-a64.o pinctrl-sun50i-a64-r.o
endif
